spring.application.name=MindCare
spring.datasource.url=jdbc:postgresql://localhost:5432/mindcare_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never
ip.frontend=http://localhost:4200
jwt.secret=0C/ZZj9OCW7Q74lUM200BayaFq6u12EKyps4NLFQNufowubX5nE1DQT8XRdwv0zUBp7Tns1DQT8XRdwv0zUBp7Tns1yhYlwzUCm3maQkg==

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
